{
  "timestamp": "2025-10-10 04:17:02",
  "total_tests": 8,
  "passed": 0,
  "failed": 8,
  "results": [
    {
      "scenario": "fc03_our-library_server_pymodbus_client",
      "server": "our-library",
      "client": "pymodbus",
      "success": false,
      "duration_ms": 6145.272493362427,
      "error_message": "",
      "pcap_file": "/pcaps/fc03_our-library_server_pymodbus_client.pcapng",
      "validation_errors": null
    },
    {
      "scenario": "fc03_our-library_server_modpoll_client",
      "server": "our-library",
      "client": "modpoll",
      "success": false,
      "duration_ms": 33049.431800842285,
      "error_message": "Command '['modpoll', '-m', 'tcp', '-a', '1', '-r', '1', '-c', '10', '-p', '5502', '127.0.0.1']' timed out after 30 seconds",
      "pcap_file": "/pcaps/fc03_our-library_server_modpoll_client.pcapng",
      "validation_errors": null
    },
    {
      "scenario": "fc03_diagslave_server_our-library_client",
      "server": "diagslave",
      "client": "our-library",
      "success": false,
      "duration_ms": 3057.284355163574,
      "error_message": "Mismatch at index 0: expected 100 got 0.\n",
      "pcap_file": "/pcaps/fc03_diagslave_server_our-library_client.pcapng",
      "validation_errors": null
    },
    {
      "scenario": "fc03_diagslave_server_pymodbus_client",
      "server": "diagslave",
      "client": "pymodbus",
      "success": false,
      "duration_ms": 3121.966600418091,
      "error_message": "Traceback (most recent call last):\n  File \"<string>\", line 10, in <module>\n  File \"/usr/local/lib/python3.10/dist-packages/pymodbus/client/mixin.py\", line 102, in read_holding_registers\n    return self.execute(\n  File \"/usr/local/lib/python3.10/dist-packages/pymodbus/client/base.py\", line 177, in execute\n    return self.transaction.execute(request)\n  File \"/usr/local/lib/python3.10/dist-packages/pymodbus/transaction.py\", line 168, in execute\n    response, last_exception = self._transact(\n  File \"/usr/local/lib/python3.10/dist-packages/pymodbus/transaction.py\", line 313, in _transact\n    result = self._recv(response_length, full)\n  File \"/usr/local/lib/python3.10/dist-packages/pymodbus/transaction.py\", line 343, in _recv\n    read_min = self.client.framer.recvPacket(min_size)\n  File \"/usr/local/lib/python3.10/dist-packages/pymodbus/framer/base.py\", line 77, in recvPacket\n    return self.client.recv(size)\n  File \"/usr/local/lib/python3.10/dist-packages/pymodbus/client/tcp.py\", line 210, in recv\n    return self._handle_abrupt_socket_close(\n  File \"/usr/local/lib/python3.10/dist-packages/pymodbus/client/tcp.py\", line 257, in _handle_abrupt_socket_close\n    raise ConnectionException(msg)\npymodbus.exceptions.ConnectionException: Modbus Error: [Connection] ModbusTcpClient(127.0.0.1:5502): Connection unexpectedly closed 0.0013306140899658203 seconds into read of 8 bytes without response from slave before it closed connection\n",
      "pcap_file": "/pcaps/fc03_diagslave_server_pymodbus_client.pcapng",
      "validation_errors": null
    },
    {
      "scenario": "fc03_diagslave_server_modpoll_client",
      "server": "diagslave",
      "client": "modpoll",
      "success": false,
      "duration_ms": 33097.782373428345,
      "error_message": "Command '['modpoll', '-m', 'tcp', '-a', '1', '-r', '1', '-c', '10', '-p', '5502', '127.0.0.1']' timed out after 30 seconds",
      "pcap_file": "/pcaps/fc03_diagslave_server_modpoll_client.pcapng",
      "validation_errors": null
    },
    {
      "scenario": "fc06_write_single_pymodbus_our_lib",
      "server": "our-library",
      "client": "pymodbus",
      "success": false,
      "duration_ms": 6132.604122161865,
      "error_message": "",
      "pcap_file": "/pcaps/fc06_write_single_pymodbus_our_lib.pcapng",
      "validation_errors": null
    },
    {
      "scenario": "fc16_write_multiple_our_lib_diagslave",
      "server": "diagslave",
      "client": "our-library",
      "success": false,
      "duration_ms": 3047.7542877197266,
      "error_message": "Mismatch at index 0: expected 1 got 0.\n",
      "pcap_file": "/pcaps/fc16_write_multiple_our_lib_diagslave.pcapng",
      "validation_errors": null
    },
    {
      "scenario": "fc03_illegal_address_exception",
      "server": "diagslave",
      "client": "our-library",
      "success": false,
      "duration_ms": 3048.145294189453,
      "error_message": null,
      "pcap_file": "/pcaps/fc03_illegal_address_exception.pcapng",
      "validation_errors": null
    }
  ]
}